name: "CI"

on:
  pull_request:
    branches: [ master ]

jobs:
  # Runs the CI build on all PRs and branches.
  build:
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout sources"
      uses: actions/checkout@v1

    - name: "Setup Java"
      uses: actions/setup-java@v1
      with:
        java-version: 15

    - name: "Run Gradle build"
      run: chmod 755 gradlew && ./gradlew build -Dci=true
      env:
        # We don't actually need AWS credentials in the tests, but the AWS SDK
        # complains if they're not there, so we add dummies to the environment.
        AWS_ACCESS_KEY_ID: ${{ secrets.DUMMY_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.DUMMY_AWS_SECRET_KEY }}
