name: "deploy package"

on:
  push:
    branches:
      - master
permissions:
  packages: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout sources"
        uses: actions/checkout@v1

      - name: "Setup Java"
        uses: actions/setup-java@v1
        with:
          java-version: 19

      - name: Publish package
        run: chmod 755 gradlew && ./gradlew publish -Dci=true
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DUMMY_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.DUMMY_AWS_SECRET_KEY }}
